export const allProducts = [
  {
    id: 1,
    image: 'https://i.imgur.com/SUAD4By.png',
    name: 'Player Plant',
    soldAmount: 4268,
    rating: 4.8,
    price: 29,
  },
  {
    id: 2,
    image: 'https://i.imgur.com/tzRUHa5.png',
    name: 'Eve Plant',
    soldAmount: 3884,
    rating: 4.7,
    price: 25,
  },
  {
    id: 3,
    image: 'https://i.imgur.com/WdcJh8w.png',
    name: 'Zoey Plant',
    soldAmount: 3884,
    rating: 4.7,
    price: 25,
  },
  {
    id: 4,
    image: 'https://i.imgur.com/doUrTmg.png',
    name: 'Sangy Plant',
    soldAmount: 3884,
    rating: 4.7,
    price: 25,
  },
  {
    id: 5,
    image: 'https://i.imgur.com/GMUzJsy.png',
    name: 'Zaza Plant',
    soldAmount: 3884,
    rating: 4.7,
    price: 25,
  },
]
